# Generated by Django 4.2.2 on 2023-06-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {("location", "date", "time")},
            },
        ),
    ]
